#!/usr/bin/env python3
"""Render a monospaced TTF into 1bpp bitmap font tables for the LCD demo.

Run from the project root; overwrites include/font12x24.h. Needs Pillow.

Emits two contiguous glyph tables -- ASCII and a Cyrillic block covering the
Russian alphabet (U+0400-U+045F: includes А-Я, а-я, Ё, ё) -- since Menlo's
codepoints aren't contiguous across both scripts.
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

W, H = 12, 24          # cell size in pixels
SIZE = 20              # point size (Menlo advance = 0.6em -> exactly 12px)

RANGES = [
    ("ASCII", "FONT", 0x20, 0x7E),
    ("Cyrillic", "FONT_CYRILLIC", 0x0400, 0x045F),
]

# Any monospaced TTF/TTC works; pass a path as argv[1] or set FONT_PATH.
# Menlo's advance is 0.6 em, so 20 pt lands exactly on the 12 px cell width.
FONT_PATH = (sys.argv[1] if len(sys.argv) > 1
             else os.environ.get("FONT_PATH", "/System/Library/Fonts/Menlo.ttc"))

font = ImageFont.truetype(FONT_PATH, SIZE, index=0)
ascent, descent = font.getmetrics()
# vertically center the ascent/descent box inside the cell
baseline = (H - (ascent + descent)) // 2 + ascent


def render_glyph(code):
    img = Image.new("1", (W, H), 0)
    d = ImageDraw.Draw(img)
    d.text((0, baseline), chr(code), font=font, fill=1, anchor="ls")
    rows = []
    for y in range(H):
        bits = 0
        for x in range(W):
            if img.getpixel((x, y)):
                bits |= 1 << (W - 1 - x)   # MSB = leftmost pixel
        rows.append(bits)
    return rows


out = ["// Generated by scripts/genfont.py -- Menlo %dpt rendered into a %dx%d cell."
       % (SIZE, W, H),
       "// 1 bit per pixel, %d rows per glyph, MSB = leftmost pixel." % H,
       "#pragma once", "", "#include <stdint.h>", "",
       "#define FONT_WIDTH  %d" % W,
       "#define FONT_HEIGHT %d" % H, ""]

all_glyphs = {}
for name, prefix, first, last in RANGES:
    out.append("#define %s_FIRST_CHAR 0x%04X" % (prefix, first))
    out.append("#define %s_LAST_CHAR  0x%04X" % (prefix, last))
out.append("")

for name, prefix, first, last in RANGES:
    glyphs = [(code, render_glyph(code)) for code in range(first, last + 1)]
    all_glyphs[prefix] = glyphs
    out.append("// %s: U+%04X - U+%04X" % (name, first, last))
    out.append("static const uint16_t %s_glyphs[%s_LAST_CHAR - %s_FIRST_CHAR + 1][FONT_HEIGHT] = {"
                % (prefix.lower(), prefix, prefix))
    for code, rows in glyphs:
        body = ", ".join("0x%04X" % r for r in rows)
        comment = chr(code) if code not in (0x5C,) else "\\\\"
        out.append("    { %s },  // U+%04X '%s'" % (body, code, comment))
    out.append("};")
    out.append("")

open("include/font12x24.h", "w").write("\n".join(out) + "\n")

# ASCII-art preview so the result can be eyeballed
preview = "Привет, Мир!"
lookup = {code: rows for code, rows in all_glyphs["FONT"] + all_glyphs["FONT_CYRILLIC"]}
for y in range(H):
    line = ""
    for ch in preview:
        rows = lookup.get(ord(ch))
        row = rows[y] if rows else 0
        line += "".join("#" if row & (1 << (W - 1 - x)) else "." for x in range(W))
    print(line)
